Execute uname instead of using the variable
Otherwise:

    Error: 'repository_os' value has no field or method 'uname' (did you mean 'name'?)

Coppied from gazelle which was coppied from rules. No reason to keep up to date though I think:

https://github.com/bazelbuild/bazel-gazelle/blob/v0.37.0/internal/go_repository_cache.bzl#L108